<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sincronizar vistas en Revit (con dynamo) - random[ ] - arquitectura y fabricación digital</title><meta name="robots" content="index, follow"><meta name="generator" content="Publii Open-Source CMS for Static Site"><link rel="canonical" href="https://dhaslock.github.io/randomarq/sincronizar-vistas-en-revit-con-dynamo.html"><link rel="amphtml" href="https://dhaslock.github.io/randomarq/amp/sincronizar-vistas-en-revit-con-dynamo.html"><link type="application/atom+xml" rel="alternate" href="https://dhaslock.github.io/randomarq/feed.xml"><meta property="og:title" content="Sincronizar vistas en Revit (con dynamo)"><meta property="og:image" content="https://dhaslock.github.io/randomarq/media/posts/6/02.JPG"><meta property="og:site_name" content="random[ ] - arquitectura y fabricación digital"><meta property="og:description" content="Hace unos días nos preguntaron si era posible tener en Revit algún comando que teniendo varias plantas abiertas a la vez, las pusiera todas&hellip;"><meta property="og:url" content="https://dhaslock.github.io/randomarq/sincronizar-vistas-en-revit-con-dynamo.html"><meta property="og:type" content="article"><link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin><link href="https://fonts.googleapis.com/css?family= PT+Serif:400,700|Muli:400,600" rel="stylesheet"><link rel="stylesheet" href="https://dhaslock.github.io/randomarq/assets/css/style.css?v=f0bad53ff3c0dc057707972ece4af300"><script type="application/ld+json">{"@context":"http://schema.org","@type":"Article","mainEntityOfPage":{"@type":"WebPage","@id":"https://dhaslock.github.io/randomarq/sincronizar-vistas-en-revit-con-dynamo.html"},"headline":"Sincronizar vistas en Revit (con dynamo)","datePublished":"2019-05-04T20:35","dateModified":"2019-05-04T20:35","image":{"@type":"ImageObject","url":"https://dhaslock.github.io/randomarq/media/posts/6/02.JPG","height":1080,"width":2560},"description":"Hace unos días nos preguntaron si era posible tener en Revit algún comando que teniendo varias plantas abiertas a la vez, las pusiera todas&hellip;","publisher":{"@type":"Organization","name":"david serrano"}}</script><script async src="https://dhaslock.github.io/randomarq/assets/js/lazysizes.min.js?v=3150bf538edc0788afd7c673a0c5dfee"></script><style></style></head><body><div class="container"><header class="js-top is-sticky"><a class="logo" href="https://dhaslock.github.io/randomarq">random[ ] - arquitectura y fabricación digital</a><div class="top"><nav class="navbar js-navbar"><button class="navbar__toggle js-navbar__toggle" aria-expanded="false">Menu</button><ul class="navbar__menu"><li class="has-submenu"><span>random[es]</span><ul class="navbar__submenu"><li><a href="https://dhaslock.github.io/randomarq/random-arquitectura-y-fabricacion-digital.html" target="_self">random[arq]</a></li><li class="has-submenu"><span>Consultoría</span><ul class="navbar__submenu"><li><span>BIM</span></li><li><span>CAD</span></li><li><span>Diseño paramétrico</span></li></ul></li><li class="has-submenu"><a href="https://dhaslock.github.io/randomarq/blog/" target="_self">Blog</a><ul class="navbar__submenu"><li><a href="https://dhaslock.github.io/randomarq/revit/" target="_self">Revit</a></li><li><span>Rhino</span></li><li><span>Arduino</span></li><li><span>Grasshopper</span></li><li><a href="https://dhaslock.github.io/randomarq/dynamo/" target="_self">Dynamo</a></li></ul></li><li><span>Contacto</span></li></ul></li><li class="has-submenu"><span>random[en]</span><ul class="navbar__submenu"><li><a href="https://dhaslock.github.io/randomarq/random-arquitectura-y-fabricacion-digital-copy.html" target="_self">about us</a></li><li class="has-submenu"><span>Training</span><ul class="navbar__submenu"><li><a href="https://dhaslock.github.io/randomarq/arduino/" target="_self">Arduino</a></li></ul></li><li><span>contact</span></li></ul></li></ul></nav></div></header><main class="u-cutting"><article class="post"><div class="post__featured-image post__image--full"><img class="lazyload" src="https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-xs.JPG" data-srcset="https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-xs.JPG 300w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-sm.JPG 480w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-md.JPG 768w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-lg.JPG 1024w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-xl.JPG 1360w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-2xl.JPG 1600w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-3xl.JPG 2560w" data-sizes="auto" height="1080" width="2560" alt=""></div><header class="post__header"><h1>Sincronizar vistas en Revit (con dynamo)</h1></header><div class="post__entry"><p>Hace unos días nos preguntaron si era posible tener en Revit algún comando que teniendo varias plantas abiertas a la vez, las pusiera todas en la misma posición y con el mismo nivel de zoom, para poder comparar diferentes plantas como si estuviéramos trabajando con capas de papel sulfurizado sobre nuestra mesa de dibujo, sin tener que usar la opción de "subyacente" del propio Revit. </p><p><img class="lazyload" src="https://dhaslock.github.io/randomarq/media/posts/6/responsive/01-xs.JPG" data-sizes="auto" data-srcset="https://dhaslock.github.io/randomarq/media/posts/6/responsive/01-xs.JPG 300w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/01-sm.JPG 480w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/01-md.JPG 768w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/01-lg.JPG 1024w" alt="" width="2560" height="1080"></p><p><img class="lazyload" src="https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-xs.JPG" data-sizes="auto" data-srcset="https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-xs.JPG 300w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-sm.JPG 480w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-md.JPG 768w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/02-lg.JPG 1024w" alt="" width="2560" height="1080"></p><p>La respuesta, como para muchas de las preguntas que nos realizan, debía de estar en Dynamo, aunque con un gran "pero". Porque para poder trabajar con las vistas abiertas, no tenemos herramientas directamente en Dynamo, sino que hay que pasar a través del API de Revit, pero afortunadamente tenemos la opción de programar nuestros propios componentes dentro de Dynamo con Python, así que después de trastear un rato con ello, llegamos a la pequeña pieza de código que nos daba la solución buscada:</p><p><code></code></p><pre>import clr

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

for uv in uidoc.GetOpenUIViews():
	if uv.ViewId.Equals( doc.ActiveView.Id ):
		uiview = uv

rect = uiview.GetZoomCorners()
exit = []
for view in uidoc.GetOpenUIViews():
	if not view.ViewId.Equals( doc.ActiveView.Id ):
		view.ZoomAndCenterRectangle(rect[0], rect[1])
		exit.append(view.ViewId)

OUT = exit
    </pre><p><code></code></p><p><img class="lazyload" src="https://dhaslock.github.io/randomarq/media/posts/6/responsive/03-xs.JPG" data-sizes="auto" data-srcset="https://dhaslock.github.io/randomarq/media/posts/6/responsive/03-xs.JPG 300w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/03-sm.JPG 480w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/03-md.JPG 768w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/03-lg.JPG 1024w" alt="" width="1122" height="477"></p><p>Tan sólo hay que copiar el código anterior en un componente de python en una nueva definición de dynamo y guardarla en nuestra carpeta de scripts. En la imagen anterior podéis ver una serie de componentes adicionales que nos permiten completar el script mostrando una lista con los nombres de las vistas actualizadas en cada ejecución. </p><p><img class="lazyload" src="https://dhaslock.github.io/randomarq/media/posts/6/responsive/04-xs.JPG" data-sizes="auto" data-srcset="https://dhaslock.github.io/randomarq/media/posts/6/responsive/04-xs.JPG 300w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/04-sm.JPG 480w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/04-md.JPG 768w ,https://dhaslock.github.io/randomarq/media/posts/6/responsive/04-lg.JPG 1024w" alt="" width="337" height="725"></p><p>A continuación podéis ver el script en funcionamiento:</p><figure class="post__video"><iframe class="lazyload" width="560" height="314" data-src="https://www.youtube.com/embed/cdZ8D6ljrTE" allowfullscreen="allowfullscreen" data-mce-fragment="1"></iframe></figure><p> </p></div></article></main><footer class="footer"><div class="footer__copyright">(-:</div></footer></div><script defer="defer" src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script><script defer="defer" src="https://dhaslock.github.io/randomarq/assets/js/scripts.min.js?v=5977caa3bd6c30eab5c559ded3288d58"></script></body></html>